# CMake generated Testfile for 
# Source directory: /Users/snazir/Documents/PlaidML/plaid_onnx/onnxruntime/cmake
# Build directory: /Users/snazir/Documents/PlaidML/plaid_onnx/onnxruntime/cmake
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(onnxruntime_test_all "/Users/snazir/Documents/PlaidML/plaid_onnx/onnxruntime/cmake/onnxruntime_test_all" "--gtest_output=xml:/Users/snazir/Documents/PlaidML/plaid_onnx/onnxruntime/cmake/onnxruntime_test_all.RelWithDebInfo.results.xml")
set_tests_properties(onnxruntime_test_all PROPERTIES  WORKING_DIRECTORY "/Users/snazir/Documents/PlaidML/plaid_onnx/onnxruntime/cmake" _BACKTRACE_TRIPLES "/Users/snazir/Documents/PlaidML/plaid_onnx/onnxruntime/cmake/onnxruntime_unittests.cmake;76;add_test;/Users/snazir/Documents/PlaidML/plaid_onnx/onnxruntime/cmake/onnxruntime_unittests.cmake;399;AddTest;/Users/snazir/Documents/PlaidML/plaid_onnx/onnxruntime/cmake/onnxruntime_unittests.cmake;0;;/Users/snazir/Documents/PlaidML/plaid_onnx/onnxruntime/cmake/CMakeLists.txt;872;include;/Users/snazir/Documents/PlaidML/plaid_onnx/onnxruntime/cmake/CMakeLists.txt;0;")
add_test(onnx_test_pytorch_converted "/Users/snazir/Documents/PlaidML/plaid_onnx/onnxruntime/cmake/onnx_test_runner" "/Users/snazir/Documents/PlaidML/plaid_onnx/onnxruntime/cmake/external/onnx/onnx/backend/test/data/pytorch-converted")
set_tests_properties(onnx_test_pytorch_converted PROPERTIES  _BACKTRACE_TRIPLES "/Users/snazir/Documents/PlaidML/plaid_onnx/onnxruntime/cmake/onnxruntime_unittests.cmake;594;add_test;/Users/snazir/Documents/PlaidML/plaid_onnx/onnxruntime/cmake/onnxruntime_unittests.cmake;0;;/Users/snazir/Documents/PlaidML/plaid_onnx/onnxruntime/cmake/CMakeLists.txt;872;include;/Users/snazir/Documents/PlaidML/plaid_onnx/onnxruntime/cmake/CMakeLists.txt;0;")
add_test(onnx_test_pytorch_operator "/Users/snazir/Documents/PlaidML/plaid_onnx/onnxruntime/cmake/onnx_test_runner" "/Users/snazir/Documents/PlaidML/plaid_onnx/onnxruntime/cmake/external/onnx/onnx/backend/test/data/pytorch-operator")
set_tests_properties(onnx_test_pytorch_operator PROPERTIES  _BACKTRACE_TRIPLES "/Users/snazir/Documents/PlaidML/plaid_onnx/onnxruntime/cmake/onnxruntime_unittests.cmake;596;add_test;/Users/snazir/Documents/PlaidML/plaid_onnx/onnxruntime/cmake/onnxruntime_unittests.cmake;0;;/Users/snazir/Documents/PlaidML/plaid_onnx/onnxruntime/cmake/CMakeLists.txt;872;include;/Users/snazir/Documents/PlaidML/plaid_onnx/onnxruntime/cmake/CMakeLists.txt;0;")
add_test(onnxruntime_shared_lib_test "/Users/snazir/Documents/PlaidML/plaid_onnx/onnxruntime/cmake/onnxruntime_shared_lib_test" "--gtest_output=xml:/Users/snazir/Documents/PlaidML/plaid_onnx/onnxruntime/cmake/onnxruntime_shared_lib_test.RelWithDebInfo.results.xml")
set_tests_properties(onnxruntime_shared_lib_test PROPERTIES  WORKING_DIRECTORY "/Users/snazir/Documents/PlaidML/plaid_onnx/onnxruntime/cmake" _BACKTRACE_TRIPLES "/Users/snazir/Documents/PlaidML/plaid_onnx/onnxruntime/cmake/onnxruntime_unittests.cmake;76;add_test;/Users/snazir/Documents/PlaidML/plaid_onnx/onnxruntime/cmake/onnxruntime_unittests.cmake;688;AddTest;/Users/snazir/Documents/PlaidML/plaid_onnx/onnxruntime/cmake/onnxruntime_unittests.cmake;0;;/Users/snazir/Documents/PlaidML/plaid_onnx/onnxruntime/cmake/CMakeLists.txt;872;include;/Users/snazir/Documents/PlaidML/plaid_onnx/onnxruntime/cmake/CMakeLists.txt;0;")
add_test(onnxruntime_global_thread_pools_test "/Users/snazir/Documents/PlaidML/plaid_onnx/onnxruntime/cmake/onnxruntime_global_thread_pools_test" "--gtest_output=xml:/Users/snazir/Documents/PlaidML/plaid_onnx/onnxruntime/cmake/onnxruntime_global_thread_pools_test.RelWithDebInfo.results.xml")
set_tests_properties(onnxruntime_global_thread_pools_test PROPERTIES  WORKING_DIRECTORY "/Users/snazir/Documents/PlaidML/plaid_onnx/onnxruntime/cmake" _BACKTRACE_TRIPLES "/Users/snazir/Documents/PlaidML/plaid_onnx/onnxruntime/cmake/onnxruntime_unittests.cmake;76;add_test;/Users/snazir/Documents/PlaidML/plaid_onnx/onnxruntime/cmake/onnxruntime_unittests.cmake;697;AddTest;/Users/snazir/Documents/PlaidML/plaid_onnx/onnxruntime/cmake/onnxruntime_unittests.cmake;0;;/Users/snazir/Documents/PlaidML/plaid_onnx/onnxruntime/cmake/CMakeLists.txt;872;include;/Users/snazir/Documents/PlaidML/plaid_onnx/onnxruntime/cmake/CMakeLists.txt;0;")
subdirs("external/googletest")
subdirs("external/nsync")
subdirs("external/protobuf/cmake")
subdirs("external/date")
subdirs("external/re2")
subdirs("onnx")
